title: "Audrey SAUSSAYE Portfolio"
description: "Bienvenue dans mon Portfolio"
baseurl: "" # le chemin de base du site, par exemple /blog
url: "https://PikaChou82.github.io" # l'URL de votre site

theme: minima

# Configuration des collections
collections:
  parcours:
    output: true

# Variables personnalisées
author:
  name: "Audrey SAUSSAYE"
  email: "audrey.saussaye@gmail.com"

# Plugins (si nécessaire)
plugins:
  - jekyll-feed
